### ISSUE TITLE
 Form generation from schema / data

### ISSUE THREAD

**Issue by HerschelC** [18F/template-form#14]
Feature request.. 

Sometimes the information that needs to be collected on a form is determined dynamically - essentially a series of forms that could guide the final form with the data we are trying to collect.  (A multi-level form generation process is also needed where branching may occur.)  A trivial example would be asking for information specific to a gender if the gender is known from a previous question.  

The form would be automatically generated from the schema of data elements (using the domain of valid attribute values as defined in the schema).  The data output would likewise be in the same schema for easy ingest into another process following the same data standard.  Another way to think of this is as subforms.  If collecting health data, and we know the person is a male, therefore ask this series of questions (populate this series of data elements).

This would somewhat turn forms management into schema management and enable the governance of individual data elements within schemas as opposed to management of static forms.  Forms, as an aggregation of elements, could be managed as well if needed - but the concept is to manage (version, govern) individual elements that could be used across any number of forms.  At the same time, this standardizes the data element definition to enable ease of reuse by another process that may need the same data element.

This line of thinking is generally based on a reporting use case.  CDC conducting a surveillance program to collect data, grantee applying for a grant or reporting on progress - really any time data may need to be collected and/or used more than once.

**Comment by lauraGgit** [comment]
See #8
